# Generated by Django 5.1 on 2024-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default="d63bd3e89b719f85be0da3fa6267b5c7bc6cfcc68ddef65ce2ee1cb7c841f0a5",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("goal", models.CharField(max_length=50)),
                ("exercise", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("bmi", models.FloatField()),
                ("bmi_category", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
