# Generated by Django 5.1 on 2024-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="allergies",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userdata",
            name="cooking_time",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="userdata",
            name="dietary_preference",
            field=models.CharField(default="no_preference", max_length=50),
        ),
        migrations.AddField(
            model_name="userdata",
            name="gender",
            field=models.CharField(default="not_selected", max_length=10),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="7292ba18079bc7690a52581c0d0f629373395728e201a719b454686fc95c74ea",
                max_length=64,
                unique=True,
            ),
        ),
    ]
