# Generated by Django 5.1 on 2024-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_userdata_allergies_userdata_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="b7b96b9fb3aec6268b0f921e6d2cae510df3fcf6150eea9238ca71a2977c4527",
                max_length=64,
                unique=True,
            ),
        ),
    ]
