# Generated by Django 5.1 on 2024-12-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_alter_userdata_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="7aa05268ce2c05e4e716f88c86fdace5f354f0a5a5dd64686d198a584e6b400c",
                max_length=64,
                unique=True,
            ),
        ),
    ]
