# Generated by Django 5.1 on 2024-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0004_alter_userdata_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="bmi",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="bmi_category",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="cooking_time",
        ),
        migrations.AddField(
            model_name="userdata",
            name="num_meals",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="dietary_preference",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="c3e35fdf5d9a4cb5c7189a8f4e4e591805ff3b079f9b18150d8b241fe1c0c798",
                max_length=64,
                unique=True,
            ),
        ),
    ]
