# Generated by Django 5.1 on 2024-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0005_remove_userdata_bmi_remove_userdata_bmi_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="b66cda4b3911766fe023eb009c47a3afc73baa9bd70150ffa907c6cea1bc76c3",
                max_length=64,
                unique=True,
            ),
        ),
    ]
