# Generated by Django 5.1 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0006_alter_userdata_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="token",
            field=models.CharField(
                default="1e3818478b35928885740d64adb637fe004c0ac2769ca604c6beb44cad165509",
                max_length=64,
                unique=True,
            ),
        ),
    ]
